# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Abbas_Setup/FYP_Material/New_PC_Progress/Improve_Latencies/MACD_Optimization/Critical_Path_Analysis/EMA_Opt/EMA12/EMA12.cache/wt [current_project]
set_property parent.project_path C:/Abbas_Setup/FYP_Material/New_PC_Progress/Improve_Latencies/MACD_Optimization/Critical_Path_Analysis/EMA_Opt/EMA12/EMA12.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_output_repo c:/Abbas_Setup/FYP_Material/New_PC_Progress/Improve_Latencies/MACD_Optimization/Critical_Path_Analysis/EMA_Opt/EMA12/EMA12.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Abbas_Setup/FYP_Material/New_PC_Progress/Improve_Latencies/MACD_Optimization/Critical_Path_Analysis/EMA_Opt/reg.vhd
  C:/Abbas_Setup/FYP_Material/New_PC_Progress/Improve_Latencies/MACD_Optimization/Critical_Path_Analysis/EMA_Opt/EMA12.vhd
  C:/Abbas_Setup/FYP_Material/New_PC_Progress/Improve_Latencies/MACD_Optimization/Critical_Path_Analysis/EMA_Opt/EMA26.vhd
  C:/Abbas_Setup/FYP_Material/New_PC_Progress/Improve_Latencies/MACD_Optimization/Critical_Path_Analysis/EMA_Opt/EMA9.vhd
  C:/Abbas_Setup/FYP_Material/New_PC_Progress/Improve_Latencies/MACD_Optimization/Critical_Path_Analysis/EMA_Opt/RAM.vhd
  C:/Abbas_Setup/FYP_Material/New_PC_Progress/Improve_Latencies/MACD_Optimization/Critical_Path_Analysis/EMA_Opt/controller.vhd
  C:/Abbas_Setup/FYP_Material/New_PC_Progress/Improve_Latencies/MACD_Optimization/Critical_Path_Analysis/EMA_Opt/counter.vhd
  C:/Abbas_Setup/FYP_Material/New_PC_Progress/Improve_Latencies/MACD_Optimization/Critical_Path_Analysis/EMA_Opt/datapath.vhd
  C:/Abbas_Setup/FYP_Material/New_PC_Progress/Improve_Latencies/MACD_Optimization/Critical_Path_Analysis/EMA_Opt/top.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Abbas_Setup/FYP_Material/New_PC_Progress/Improve_Latencies/MACD_Optimization/Critical_Path_Analysis/EMA_Opt/EMA12/EMA12.srcs/constrs_1/new/clk.xdc
set_property used_in_implementation false [get_files C:/Abbas_Setup/FYP_Material/New_PC_Progress/Improve_Latencies/MACD_Optimization/Critical_Path_Analysis/EMA_Opt/EMA12/EMA12.srcs/constrs_1/new/clk.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
